// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: rune_utxo_service.proto

package rune_utxo_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RuneUtxoService_FetchAddressRuneBalanceList_FullMethodName = "/protobuf.RuneUtxoService/FetchAddressRuneBalanceList"
	RuneUtxoService_FetchAddressRuneBalanceInfo_FullMethodName = "/protobuf.RuneUtxoService/FetchAddressRuneBalanceInfo"
	RuneUtxoService_FetchRuneUtxoInfo_FullMethodName           = "/protobuf.RuneUtxoService/FetchRuneUtxoInfo"
	RuneUtxoService_FetchAddressRuneUtxoList_FullMethodName    = "/protobuf.RuneUtxoService/FetchAddressRuneUtxoList"
	RuneUtxoService_FetchRuneUtxoCheck_FullMethodName          = "/protobuf.RuneUtxoService/FetchRuneUtxoCheck"
	RuneUtxoService_BatchFetchRuneUtxoCheck_FullMethodName     = "/protobuf.RuneUtxoService/BatchFetchRuneUtxoCheck"
	RuneUtxoService_FetchAddressRuneUtxoBalance_FullMethodName = "/protobuf.RuneUtxoService/FetchAddressRuneUtxoBalance"
	RuneUtxoService_FetchAddressRuneTxList_FullMethodName      = "/protobuf.RuneUtxoService/FetchAddressRuneTxList"
)

// RuneUtxoServiceClient is the client API for RuneUtxoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuneUtxoServiceClient interface {
	FetchAddressRuneBalanceList(ctx context.Context, in *AddressRuneBalanceInfoListRequest, opts ...grpc.CallOption) (*RuneBalanceInfoListResponse, error)
	FetchAddressRuneBalanceInfo(ctx context.Context, in *AddressRuneBalanceInfoRequest, opts ...grpc.CallOption) (*RuneBalanceInfoResponse, error)
	FetchRuneUtxoInfo(ctx context.Context, in *RuneUtxoRequest, opts ...grpc.CallOption) (*RuneUtxoInfoListResponse, error)
	FetchAddressRuneUtxoList(ctx context.Context, in *AddressRuneUtxoRequest, opts ...grpc.CallOption) (*RuneUtxoListResponse, error)
	FetchRuneUtxoCheck(ctx context.Context, in *RuneUtxoCheckRequest, opts ...grpc.CallOption) (*RuneUtxoCheckResponse, error)
	BatchFetchRuneUtxoCheck(ctx context.Context, in *BatchUtxoCheckRequest, opts ...grpc.CallOption) (*BatchRuneUtxoCheckResponse, error)
	FetchAddressRuneUtxoBalance(ctx context.Context, in *AddressRuneUtxoBalanceRequest, opts ...grpc.CallOption) (*AddressRuneUtxoBalanceResponse, error)
	FetchAddressRuneTxList(ctx context.Context, in *AddressRuneTxRequest, opts ...grpc.CallOption) (*RuneTxListResponse, error)
}

type runeUtxoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuneUtxoServiceClient(cc grpc.ClientConnInterface) RuneUtxoServiceClient {
	return &runeUtxoServiceClient{cc}
}

func (c *runeUtxoServiceClient) FetchAddressRuneBalanceList(ctx context.Context, in *AddressRuneBalanceInfoListRequest, opts ...grpc.CallOption) (*RuneBalanceInfoListResponse, error) {
	out := new(RuneBalanceInfoListResponse)
	err := c.cc.Invoke(ctx, RuneUtxoService_FetchAddressRuneBalanceList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeUtxoServiceClient) FetchAddressRuneBalanceInfo(ctx context.Context, in *AddressRuneBalanceInfoRequest, opts ...grpc.CallOption) (*RuneBalanceInfoResponse, error) {
	out := new(RuneBalanceInfoResponse)
	err := c.cc.Invoke(ctx, RuneUtxoService_FetchAddressRuneBalanceInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeUtxoServiceClient) FetchRuneUtxoInfo(ctx context.Context, in *RuneUtxoRequest, opts ...grpc.CallOption) (*RuneUtxoInfoListResponse, error) {
	out := new(RuneUtxoInfoListResponse)
	err := c.cc.Invoke(ctx, RuneUtxoService_FetchRuneUtxoInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeUtxoServiceClient) FetchAddressRuneUtxoList(ctx context.Context, in *AddressRuneUtxoRequest, opts ...grpc.CallOption) (*RuneUtxoListResponse, error) {
	out := new(RuneUtxoListResponse)
	err := c.cc.Invoke(ctx, RuneUtxoService_FetchAddressRuneUtxoList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeUtxoServiceClient) FetchRuneUtxoCheck(ctx context.Context, in *RuneUtxoCheckRequest, opts ...grpc.CallOption) (*RuneUtxoCheckResponse, error) {
	out := new(RuneUtxoCheckResponse)
	err := c.cc.Invoke(ctx, RuneUtxoService_FetchRuneUtxoCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeUtxoServiceClient) BatchFetchRuneUtxoCheck(ctx context.Context, in *BatchUtxoCheckRequest, opts ...grpc.CallOption) (*BatchRuneUtxoCheckResponse, error) {
	out := new(BatchRuneUtxoCheckResponse)
	err := c.cc.Invoke(ctx, RuneUtxoService_BatchFetchRuneUtxoCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeUtxoServiceClient) FetchAddressRuneUtxoBalance(ctx context.Context, in *AddressRuneUtxoBalanceRequest, opts ...grpc.CallOption) (*AddressRuneUtxoBalanceResponse, error) {
	out := new(AddressRuneUtxoBalanceResponse)
	err := c.cc.Invoke(ctx, RuneUtxoService_FetchAddressRuneUtxoBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runeUtxoServiceClient) FetchAddressRuneTxList(ctx context.Context, in *AddressRuneTxRequest, opts ...grpc.CallOption) (*RuneTxListResponse, error) {
	out := new(RuneTxListResponse)
	err := c.cc.Invoke(ctx, RuneUtxoService_FetchAddressRuneTxList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuneUtxoServiceServer is the server API for RuneUtxoService service.
// All implementations must embed UnimplementedRuneUtxoServiceServer
// for forward compatibility
type RuneUtxoServiceServer interface {
	FetchAddressRuneBalanceList(context.Context, *AddressRuneBalanceInfoListRequest) (*RuneBalanceInfoListResponse, error)
	FetchAddressRuneBalanceInfo(context.Context, *AddressRuneBalanceInfoRequest) (*RuneBalanceInfoResponse, error)
	FetchRuneUtxoInfo(context.Context, *RuneUtxoRequest) (*RuneUtxoInfoListResponse, error)
	FetchAddressRuneUtxoList(context.Context, *AddressRuneUtxoRequest) (*RuneUtxoListResponse, error)
	FetchRuneUtxoCheck(context.Context, *RuneUtxoCheckRequest) (*RuneUtxoCheckResponse, error)
	BatchFetchRuneUtxoCheck(context.Context, *BatchUtxoCheckRequest) (*BatchRuneUtxoCheckResponse, error)
	FetchAddressRuneUtxoBalance(context.Context, *AddressRuneUtxoBalanceRequest) (*AddressRuneUtxoBalanceResponse, error)
	FetchAddressRuneTxList(context.Context, *AddressRuneTxRequest) (*RuneTxListResponse, error)
	mustEmbedUnimplementedRuneUtxoServiceServer()
}

// UnimplementedRuneUtxoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRuneUtxoServiceServer struct {
}

func (UnimplementedRuneUtxoServiceServer) FetchAddressRuneBalanceList(context.Context, *AddressRuneBalanceInfoListRequest) (*RuneBalanceInfoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAddressRuneBalanceList not implemented")
}
func (UnimplementedRuneUtxoServiceServer) FetchAddressRuneBalanceInfo(context.Context, *AddressRuneBalanceInfoRequest) (*RuneBalanceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAddressRuneBalanceInfo not implemented")
}
func (UnimplementedRuneUtxoServiceServer) FetchRuneUtxoInfo(context.Context, *RuneUtxoRequest) (*RuneUtxoInfoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRuneUtxoInfo not implemented")
}
func (UnimplementedRuneUtxoServiceServer) FetchAddressRuneUtxoList(context.Context, *AddressRuneUtxoRequest) (*RuneUtxoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAddressRuneUtxoList not implemented")
}
func (UnimplementedRuneUtxoServiceServer) FetchRuneUtxoCheck(context.Context, *RuneUtxoCheckRequest) (*RuneUtxoCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRuneUtxoCheck not implemented")
}
func (UnimplementedRuneUtxoServiceServer) BatchFetchRuneUtxoCheck(context.Context, *BatchUtxoCheckRequest) (*BatchRuneUtxoCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchFetchRuneUtxoCheck not implemented")
}
func (UnimplementedRuneUtxoServiceServer) FetchAddressRuneUtxoBalance(context.Context, *AddressRuneUtxoBalanceRequest) (*AddressRuneUtxoBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAddressRuneUtxoBalance not implemented")
}
func (UnimplementedRuneUtxoServiceServer) FetchAddressRuneTxList(context.Context, *AddressRuneTxRequest) (*RuneTxListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAddressRuneTxList not implemented")
}
func (UnimplementedRuneUtxoServiceServer) mustEmbedUnimplementedRuneUtxoServiceServer() {}

// UnsafeRuneUtxoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuneUtxoServiceServer will
// result in compilation errors.
type UnsafeRuneUtxoServiceServer interface {
	mustEmbedUnimplementedRuneUtxoServiceServer()
}

func RegisterRuneUtxoServiceServer(s grpc.ServiceRegistrar, srv RuneUtxoServiceServer) {
	s.RegisterService(&RuneUtxoService_ServiceDesc, srv)
}

func _RuneUtxoService_FetchAddressRuneBalanceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRuneBalanceInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneBalanceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneUtxoService_FetchAddressRuneBalanceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneBalanceList(ctx, req.(*AddressRuneBalanceInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneUtxoService_FetchAddressRuneBalanceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRuneBalanceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneBalanceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneUtxoService_FetchAddressRuneBalanceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneBalanceInfo(ctx, req.(*AddressRuneBalanceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneUtxoService_FetchRuneUtxoInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuneUtxoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneUtxoServiceServer).FetchRuneUtxoInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneUtxoService_FetchRuneUtxoInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneUtxoServiceServer).FetchRuneUtxoInfo(ctx, req.(*RuneUtxoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneUtxoService_FetchAddressRuneUtxoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRuneUtxoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneUtxoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneUtxoService_FetchAddressRuneUtxoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneUtxoList(ctx, req.(*AddressRuneUtxoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneUtxoService_FetchRuneUtxoCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuneUtxoCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneUtxoServiceServer).FetchRuneUtxoCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneUtxoService_FetchRuneUtxoCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneUtxoServiceServer).FetchRuneUtxoCheck(ctx, req.(*RuneUtxoCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneUtxoService_BatchFetchRuneUtxoCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUtxoCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneUtxoServiceServer).BatchFetchRuneUtxoCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneUtxoService_BatchFetchRuneUtxoCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneUtxoServiceServer).BatchFetchRuneUtxoCheck(ctx, req.(*BatchUtxoCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneUtxoService_FetchAddressRuneUtxoBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRuneUtxoBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneUtxoBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneUtxoService_FetchAddressRuneUtxoBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneUtxoBalance(ctx, req.(*AddressRuneUtxoBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuneUtxoService_FetchAddressRuneTxList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRuneTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneTxList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuneUtxoService_FetchAddressRuneTxList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuneUtxoServiceServer).FetchAddressRuneTxList(ctx, req.(*AddressRuneTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuneUtxoService_ServiceDesc is the grpc.ServiceDesc for RuneUtxoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuneUtxoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.RuneUtxoService",
	HandlerType: (*RuneUtxoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchAddressRuneBalanceList",
			Handler:    _RuneUtxoService_FetchAddressRuneBalanceList_Handler,
		},
		{
			MethodName: "FetchAddressRuneBalanceInfo",
			Handler:    _RuneUtxoService_FetchAddressRuneBalanceInfo_Handler,
		},
		{
			MethodName: "FetchRuneUtxoInfo",
			Handler:    _RuneUtxoService_FetchRuneUtxoInfo_Handler,
		},
		{
			MethodName: "FetchAddressRuneUtxoList",
			Handler:    _RuneUtxoService_FetchAddressRuneUtxoList_Handler,
		},
		{
			MethodName: "FetchRuneUtxoCheck",
			Handler:    _RuneUtxoService_FetchRuneUtxoCheck_Handler,
		},
		{
			MethodName: "BatchFetchRuneUtxoCheck",
			Handler:    _RuneUtxoService_BatchFetchRuneUtxoCheck_Handler,
		},
		{
			MethodName: "FetchAddressRuneUtxoBalance",
			Handler:    _RuneUtxoService_FetchAddressRuneUtxoBalance_Handler,
		},
		{
			MethodName: "FetchAddressRuneTxList",
			Handler:    _RuneUtxoService_FetchAddressRuneTxList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rune_utxo_service.proto",
}
