// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: mrc20_utxo_service.proto

package mrc20_utxo_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Mrc20UtxoService_FetchMrc20AddressTxList_FullMethodName      = "/protobuf.Mrc20UtxoService/FetchMrc20AddressTxList"
	Mrc20UtxoService_FetchMrc20AddressBalanceList_FullMethodName = "/protobuf.Mrc20UtxoService/FetchMrc20AddressBalanceList"
	Mrc20UtxoService_FetchMrc20AddressUtxoList_FullMethodName    = "/protobuf.Mrc20UtxoService/FetchMrc20AddressUtxoList"
	Mrc20UtxoService_FetchMrc20DeployList_FullMethodName         = "/protobuf.Mrc20UtxoService/FetchMrc20DeployList"
	Mrc20UtxoService_FetchMrc20UtxoTxPoint_FullMethodName        = "/protobuf.Mrc20UtxoService/FetchMrc20UtxoTxPoint"
	Mrc20UtxoService_FetchMrc20UtxoTickBlock_FullMethodName      = "/protobuf.Mrc20UtxoService/FetchMrc20UtxoTickBlock"
	Mrc20UtxoService_FetchMrc20CheckBlock_FullMethodName         = "/protobuf.Mrc20UtxoService/FetchMrc20CheckBlock"
)

// Mrc20UtxoServiceClient is the client API for Mrc20UtxoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Mrc20UtxoServiceClient interface {
	FetchMrc20AddressTxList(ctx context.Context, in *AddressMrc20TxRequest, opts ...grpc.CallOption) (*Mrc20TxListResponse, error)
	FetchMrc20AddressBalanceList(ctx context.Context, in *AddressMrc20BalanceRequest, opts ...grpc.CallOption) (*Mrc20BalanceListResponse, error)
	FetchMrc20AddressUtxoList(ctx context.Context, in *AddressMrc20UtxoRequest, opts ...grpc.CallOption) (*Mrc20UtxoResponse, error)
	FetchMrc20DeployList(ctx context.Context, in *TickListRequest, opts ...grpc.CallOption) (*Mrc20DeployListResponse, error)
	FetchMrc20UtxoTxPoint(ctx context.Context, in *Mrc20UtxoTxPointRequest, opts ...grpc.CallOption) (*Mrc20DbUtxoResponse, error)
	FetchMrc20UtxoTickBlock(ctx context.Context, in *Mrc20UtxoTickBlockRequest, opts ...grpc.CallOption) (*Mrc20DbUtxoResponse, error)
	FetchMrc20CheckBlock(ctx context.Context, in *Mrc20CheckBlockRequest, opts ...grpc.CallOption) (*Mrc20CheckBlockInfoResponse, error)
}

type mrc20UtxoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMrc20UtxoServiceClient(cc grpc.ClientConnInterface) Mrc20UtxoServiceClient {
	return &mrc20UtxoServiceClient{cc}
}

func (c *mrc20UtxoServiceClient) FetchMrc20AddressTxList(ctx context.Context, in *AddressMrc20TxRequest, opts ...grpc.CallOption) (*Mrc20TxListResponse, error) {
	out := new(Mrc20TxListResponse)
	err := c.cc.Invoke(ctx, Mrc20UtxoService_FetchMrc20AddressTxList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mrc20UtxoServiceClient) FetchMrc20AddressBalanceList(ctx context.Context, in *AddressMrc20BalanceRequest, opts ...grpc.CallOption) (*Mrc20BalanceListResponse, error) {
	out := new(Mrc20BalanceListResponse)
	err := c.cc.Invoke(ctx, Mrc20UtxoService_FetchMrc20AddressBalanceList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mrc20UtxoServiceClient) FetchMrc20AddressUtxoList(ctx context.Context, in *AddressMrc20UtxoRequest, opts ...grpc.CallOption) (*Mrc20UtxoResponse, error) {
	out := new(Mrc20UtxoResponse)
	err := c.cc.Invoke(ctx, Mrc20UtxoService_FetchMrc20AddressUtxoList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mrc20UtxoServiceClient) FetchMrc20DeployList(ctx context.Context, in *TickListRequest, opts ...grpc.CallOption) (*Mrc20DeployListResponse, error) {
	out := new(Mrc20DeployListResponse)
	err := c.cc.Invoke(ctx, Mrc20UtxoService_FetchMrc20DeployList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mrc20UtxoServiceClient) FetchMrc20UtxoTxPoint(ctx context.Context, in *Mrc20UtxoTxPointRequest, opts ...grpc.CallOption) (*Mrc20DbUtxoResponse, error) {
	out := new(Mrc20DbUtxoResponse)
	err := c.cc.Invoke(ctx, Mrc20UtxoService_FetchMrc20UtxoTxPoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mrc20UtxoServiceClient) FetchMrc20UtxoTickBlock(ctx context.Context, in *Mrc20UtxoTickBlockRequest, opts ...grpc.CallOption) (*Mrc20DbUtxoResponse, error) {
	out := new(Mrc20DbUtxoResponse)
	err := c.cc.Invoke(ctx, Mrc20UtxoService_FetchMrc20UtxoTickBlock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mrc20UtxoServiceClient) FetchMrc20CheckBlock(ctx context.Context, in *Mrc20CheckBlockRequest, opts ...grpc.CallOption) (*Mrc20CheckBlockInfoResponse, error) {
	out := new(Mrc20CheckBlockInfoResponse)
	err := c.cc.Invoke(ctx, Mrc20UtxoService_FetchMrc20CheckBlock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Mrc20UtxoServiceServer is the server API for Mrc20UtxoService service.
// All implementations must embed UnimplementedMrc20UtxoServiceServer
// for forward compatibility
type Mrc20UtxoServiceServer interface {
	FetchMrc20AddressTxList(context.Context, *AddressMrc20TxRequest) (*Mrc20TxListResponse, error)
	FetchMrc20AddressBalanceList(context.Context, *AddressMrc20BalanceRequest) (*Mrc20BalanceListResponse, error)
	FetchMrc20AddressUtxoList(context.Context, *AddressMrc20UtxoRequest) (*Mrc20UtxoResponse, error)
	FetchMrc20DeployList(context.Context, *TickListRequest) (*Mrc20DeployListResponse, error)
	FetchMrc20UtxoTxPoint(context.Context, *Mrc20UtxoTxPointRequest) (*Mrc20DbUtxoResponse, error)
	FetchMrc20UtxoTickBlock(context.Context, *Mrc20UtxoTickBlockRequest) (*Mrc20DbUtxoResponse, error)
	FetchMrc20CheckBlock(context.Context, *Mrc20CheckBlockRequest) (*Mrc20CheckBlockInfoResponse, error)
	mustEmbedUnimplementedMrc20UtxoServiceServer()
}

// UnimplementedMrc20UtxoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMrc20UtxoServiceServer struct {
}

func (UnimplementedMrc20UtxoServiceServer) FetchMrc20AddressTxList(context.Context, *AddressMrc20TxRequest) (*Mrc20TxListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMrc20AddressTxList not implemented")
}
func (UnimplementedMrc20UtxoServiceServer) FetchMrc20AddressBalanceList(context.Context, *AddressMrc20BalanceRequest) (*Mrc20BalanceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMrc20AddressBalanceList not implemented")
}
func (UnimplementedMrc20UtxoServiceServer) FetchMrc20AddressUtxoList(context.Context, *AddressMrc20UtxoRequest) (*Mrc20UtxoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMrc20AddressUtxoList not implemented")
}
func (UnimplementedMrc20UtxoServiceServer) FetchMrc20DeployList(context.Context, *TickListRequest) (*Mrc20DeployListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMrc20DeployList not implemented")
}
func (UnimplementedMrc20UtxoServiceServer) FetchMrc20UtxoTxPoint(context.Context, *Mrc20UtxoTxPointRequest) (*Mrc20DbUtxoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMrc20UtxoTxPoint not implemented")
}
func (UnimplementedMrc20UtxoServiceServer) FetchMrc20UtxoTickBlock(context.Context, *Mrc20UtxoTickBlockRequest) (*Mrc20DbUtxoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMrc20UtxoTickBlock not implemented")
}
func (UnimplementedMrc20UtxoServiceServer) FetchMrc20CheckBlock(context.Context, *Mrc20CheckBlockRequest) (*Mrc20CheckBlockInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMrc20CheckBlock not implemented")
}
func (UnimplementedMrc20UtxoServiceServer) mustEmbedUnimplementedMrc20UtxoServiceServer() {}

// UnsafeMrc20UtxoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Mrc20UtxoServiceServer will
// result in compilation errors.
type UnsafeMrc20UtxoServiceServer interface {
	mustEmbedUnimplementedMrc20UtxoServiceServer()
}

func RegisterMrc20UtxoServiceServer(s grpc.ServiceRegistrar, srv Mrc20UtxoServiceServer) {
	s.RegisterService(&Mrc20UtxoService_ServiceDesc, srv)
}

func _Mrc20UtxoService_FetchMrc20AddressTxList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressMrc20TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20AddressTxList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mrc20UtxoService_FetchMrc20AddressTxList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20AddressTxList(ctx, req.(*AddressMrc20TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mrc20UtxoService_FetchMrc20AddressBalanceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressMrc20BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20AddressBalanceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mrc20UtxoService_FetchMrc20AddressBalanceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20AddressBalanceList(ctx, req.(*AddressMrc20BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mrc20UtxoService_FetchMrc20AddressUtxoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressMrc20UtxoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20AddressUtxoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mrc20UtxoService_FetchMrc20AddressUtxoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20AddressUtxoList(ctx, req.(*AddressMrc20UtxoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mrc20UtxoService_FetchMrc20DeployList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20DeployList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mrc20UtxoService_FetchMrc20DeployList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20DeployList(ctx, req.(*TickListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mrc20UtxoService_FetchMrc20UtxoTxPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mrc20UtxoTxPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20UtxoTxPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mrc20UtxoService_FetchMrc20UtxoTxPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20UtxoTxPoint(ctx, req.(*Mrc20UtxoTxPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mrc20UtxoService_FetchMrc20UtxoTickBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mrc20UtxoTickBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20UtxoTickBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mrc20UtxoService_FetchMrc20UtxoTickBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20UtxoTickBlock(ctx, req.(*Mrc20UtxoTickBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mrc20UtxoService_FetchMrc20CheckBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mrc20CheckBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20CheckBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mrc20UtxoService_FetchMrc20CheckBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mrc20UtxoServiceServer).FetchMrc20CheckBlock(ctx, req.(*Mrc20CheckBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mrc20UtxoService_ServiceDesc is the grpc.ServiceDesc for Mrc20UtxoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mrc20UtxoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Mrc20UtxoService",
	HandlerType: (*Mrc20UtxoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchMrc20AddressTxList",
			Handler:    _Mrc20UtxoService_FetchMrc20AddressTxList_Handler,
		},
		{
			MethodName: "FetchMrc20AddressBalanceList",
			Handler:    _Mrc20UtxoService_FetchMrc20AddressBalanceList_Handler,
		},
		{
			MethodName: "FetchMrc20AddressUtxoList",
			Handler:    _Mrc20UtxoService_FetchMrc20AddressUtxoList_Handler,
		},
		{
			MethodName: "FetchMrc20DeployList",
			Handler:    _Mrc20UtxoService_FetchMrc20DeployList_Handler,
		},
		{
			MethodName: "FetchMrc20UtxoTxPoint",
			Handler:    _Mrc20UtxoService_FetchMrc20UtxoTxPoint_Handler,
		},
		{
			MethodName: "FetchMrc20UtxoTickBlock",
			Handler:    _Mrc20UtxoService_FetchMrc20UtxoTickBlock_Handler,
		},
		{
			MethodName: "FetchMrc20CheckBlock",
			Handler:    _Mrc20UtxoService_FetchMrc20CheckBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mrc20_utxo_service.proto",
}
