syntax = "proto3";
option go_package = "./protobuf/mrc20_utxo_service";

package protobuf;

message AddressMrc20TxRequest {
  string address = 1;
  string tickId = 2;
  int64 offset = 3;
  int64 limit = 4;
}


message Mrc20TxListResponse {
  int64 total = 1;
  int64 offset = 2;
  repeated Mrc20TxInfoResponse detail = 3;
}

message Mrc20TxInfoResponse {
  string txId = 1;
  string tickId = 2;
  string tick = 3;
  string tokenName = 4;
  int64 decimals = 5;
  string metadata = 6;
  string from = 7;
  string to = 8;
  string amount = 9;
  int64 txType = 10;
  int64 timestamp = 11;
}



message AddressMrc20BalanceRequest {
  string address = 1;
  repeated string tickIds = 2;
  int64 offset = 3;
  int64 limit = 4;
}

message Mrc20BalanceListResponse {
  int64 total = 1;
  int64 offset = 2;
  repeated Mrc20BalanceInfoResponse detail = 3;
}

message Mrc20BalanceInfoResponse {
  string tickId = 1;
  string tick = 2;
  string tokenName = 3;
  int64 decimals = 4;
  string balance = 5;
  string metadata = 6;
}




message AddressMrc20UtxoRequest {
  string address = 1;
  repeated string tickIds = 2;
  int64 offset = 3;
  int64 limit = 4;
}


message Mrc20UtxoResponse {
  int64 total = 1;
  int64 offset = 2;
  repeated Mrc20UtxoInfo detail = 3;
}

message Mrc20UtxoInfo {
  string chain = 1;
  int64 blockHeight = 2;
  string address = 3;
  int64 satoshi = 4;
  int64 satoshis = 5;
  string scriptPk = 6;
  string txId = 7;
  int64 vout = 8;
  int64 outputIndex = 9;
  repeated Mrc20Info mrc20s = 10;
  int64 mrc20Total = 11;
  int64 timestamp = 12;
}
message Mrc20Info {
  string tick = 1;
  string mrc20Id = 2;
  string txPoint = 3;
  string amount = 4;
  string decimals = 5;
}

message TickListRequest {
  string tick = 1;
  string completed = 2;
  string order = 3;
  string orderType = 4;
  int64 offset = 5;
  int64 size = 6;
}


message Mrc20DeployInfoResponse {
  string tick = 1;
  string tokenName = 2;
  string decimals = 3;
  string amtPerMint = 4;
  int64 mintCount = 5;
  string beginHeight = 6;
  string endHeight = 7;
  string metadata = 8;
  string deployType = 9;
  int64 premineCount = 10;
  Mrc20DeployPinCheck pinCheck = 11;
  PayCheck payCheck = 12;
  int64 totalMinted = 13;
  string mrc20Id = 14;
  int64 pinNumber = 15;
  string chain = 16;
  int64 holders = 17;
  int64 txCount = 18;
  string metaId = 19;
  string address = 20;
  int64 deployTime = 21;
}

message Mrc20DeployPinCheck {
  string creator = 1;
  string lvl = 2;
  string path = 3;
  string count = 4;
}

message PayCheck {
  string payTo = 1;
  string payAmount = 2;
}

message Mrc20DeployListResponse {
  int64 total = 1;
  int64 offset = 2;
  repeated Mrc20DeployInfoResponse detail = 3;
}

message Mrc20UtxoTxPointRequest {
  string txId = 1;
  int64 vout = 2;
  int64 offset = 3;
  int64 limit = 4;
}

message Mrc20UtxoTickBlockRequest {
  string tickId = 1;
  int64 blockHeight = 2;
  string mrcOption = 3;
  string address = 4;
  int64 offset = 5;
  int64 limit = 6;
}

message Mrc20DbUtxoResponse {
  int64 total = 1;
  int64 offset = 2;
  repeated Mrc20UtxoDbInfo detail = 3;
}


message Mrc20UtxoDbInfo {
  string tick = 1;
  string mrc20Id = 2;
  string txPoint = 3;
  int64 pointValue = 4;
  string pinId = 5;
  string pinContent = 6;
  bool verify = 7;
  int64 blockHeight = 8;
  string mrcOption = 9;
  string fromAddress = 10;
  string toAddress = 11;
  string msg = 12;
  string amtChange = 13;
  int64 status = 14;
  string chain = 15;
  int64 index = 16;
  int64 timestamp = 17;
}

service Mrc20UtxoService {
  rpc FetchMrc20AddressTxList(AddressMrc20TxRequest) returns (Mrc20TxListResponse) {};
  rpc FetchMrc20AddressBalanceList(AddressMrc20BalanceRequest) returns (Mrc20BalanceListResponse) {};
  rpc FetchMrc20AddressUtxoList(AddressMrc20UtxoRequest) returns (Mrc20UtxoResponse) {};
  rpc FetchMrc20DeployList(TickListRequest) returns (Mrc20DeployListResponse) {};
  rpc FetchMrc20UtxoTxPoint(Mrc20UtxoTxPointRequest) returns (Mrc20DbUtxoResponse) {};
  rpc FetchMrc20UtxoTickBlock(Mrc20UtxoTickBlockRequest) returns (Mrc20DbUtxoResponse) {};
}