// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: etching_info_service.proto

package etching_info_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EtchingService_FetchEtchingInfo_FullMethodName  = "/protobuf.EtchingService/FetchEtchingInfo"
	EtchingService_SearchEtchingList_FullMethodName = "/protobuf.EtchingService/SearchEtchingList"
)

// EtchingServiceClient is the client API for EtchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EtchingServiceClient interface {
	FetchEtchingInfo(ctx context.Context, in *EtchingInfoRequest, opts ...grpc.CallOption) (*EtchingInfoResponse, error)
	SearchEtchingList(ctx context.Context, in *SearchEtchingListRequest, opts ...grpc.CallOption) (*EtchingInfoListResponse, error)
}

type etchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEtchingServiceClient(cc grpc.ClientConnInterface) EtchingServiceClient {
	return &etchingServiceClient{cc}
}

func (c *etchingServiceClient) FetchEtchingInfo(ctx context.Context, in *EtchingInfoRequest, opts ...grpc.CallOption) (*EtchingInfoResponse, error) {
	out := new(EtchingInfoResponse)
	err := c.cc.Invoke(ctx, EtchingService_FetchEtchingInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etchingServiceClient) SearchEtchingList(ctx context.Context, in *SearchEtchingListRequest, opts ...grpc.CallOption) (*EtchingInfoListResponse, error) {
	out := new(EtchingInfoListResponse)
	err := c.cc.Invoke(ctx, EtchingService_SearchEtchingList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EtchingServiceServer is the server API for EtchingService service.
// All implementations must embed UnimplementedEtchingServiceServer
// for forward compatibility
type EtchingServiceServer interface {
	FetchEtchingInfo(context.Context, *EtchingInfoRequest) (*EtchingInfoResponse, error)
	SearchEtchingList(context.Context, *SearchEtchingListRequest) (*EtchingInfoListResponse, error)
	mustEmbedUnimplementedEtchingServiceServer()
}

// UnimplementedEtchingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEtchingServiceServer struct {
}

func (UnimplementedEtchingServiceServer) FetchEtchingInfo(context.Context, *EtchingInfoRequest) (*EtchingInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchEtchingInfo not implemented")
}
func (UnimplementedEtchingServiceServer) SearchEtchingList(context.Context, *SearchEtchingListRequest) (*EtchingInfoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchEtchingList not implemented")
}
func (UnimplementedEtchingServiceServer) mustEmbedUnimplementedEtchingServiceServer() {}

// UnsafeEtchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EtchingServiceServer will
// result in compilation errors.
type UnsafeEtchingServiceServer interface {
	mustEmbedUnimplementedEtchingServiceServer()
}

func RegisterEtchingServiceServer(s grpc.ServiceRegistrar, srv EtchingServiceServer) {
	s.RegisterService(&EtchingService_ServiceDesc, srv)
}

func _EtchingService_FetchEtchingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EtchingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtchingServiceServer).FetchEtchingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtchingService_FetchEtchingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtchingServiceServer).FetchEtchingInfo(ctx, req.(*EtchingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EtchingService_SearchEtchingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEtchingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtchingServiceServer).SearchEtchingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtchingService_SearchEtchingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtchingServiceServer).SearchEtchingList(ctx, req.(*SearchEtchingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EtchingService_ServiceDesc is the grpc.ServiceDesc for EtchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EtchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.EtchingService",
	HandlerType: (*EtchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchEtchingInfo",
			Handler:    _EtchingService_FetchEtchingInfo_Handler,
		},
		{
			MethodName: "SearchEtchingList",
			Handler:    _EtchingService_SearchEtchingList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "etching_info_service.proto",
}
