// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: mrc20_holders_service.proto

package mrc20_holders_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Mrc20HoldersService_FetchMrc20TickHolders_FullMethodName = "/protobuf.Mrc20HoldersService/FetchMrc20TickHolders"
)

// Mrc20HoldersServiceClient is the client API for Mrc20HoldersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Mrc20HoldersServiceClient interface {
	FetchMrc20TickHolders(ctx context.Context, in *Mrc20TickHoldersRequest, opts ...grpc.CallOption) (*Mrc20TickHoldersResponse, error)
}

type mrc20HoldersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMrc20HoldersServiceClient(cc grpc.ClientConnInterface) Mrc20HoldersServiceClient {
	return &mrc20HoldersServiceClient{cc}
}

func (c *mrc20HoldersServiceClient) FetchMrc20TickHolders(ctx context.Context, in *Mrc20TickHoldersRequest, opts ...grpc.CallOption) (*Mrc20TickHoldersResponse, error) {
	out := new(Mrc20TickHoldersResponse)
	err := c.cc.Invoke(ctx, Mrc20HoldersService_FetchMrc20TickHolders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Mrc20HoldersServiceServer is the server API for Mrc20HoldersService service.
// All implementations must embed UnimplementedMrc20HoldersServiceServer
// for forward compatibility
type Mrc20HoldersServiceServer interface {
	FetchMrc20TickHolders(context.Context, *Mrc20TickHoldersRequest) (*Mrc20TickHoldersResponse, error)
	mustEmbedUnimplementedMrc20HoldersServiceServer()
}

// UnimplementedMrc20HoldersServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMrc20HoldersServiceServer struct {
}

func (UnimplementedMrc20HoldersServiceServer) FetchMrc20TickHolders(context.Context, *Mrc20TickHoldersRequest) (*Mrc20TickHoldersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchMrc20TickHolders not implemented")
}
func (UnimplementedMrc20HoldersServiceServer) mustEmbedUnimplementedMrc20HoldersServiceServer() {}

// UnsafeMrc20HoldersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Mrc20HoldersServiceServer will
// result in compilation errors.
type UnsafeMrc20HoldersServiceServer interface {
	mustEmbedUnimplementedMrc20HoldersServiceServer()
}

func RegisterMrc20HoldersServiceServer(s grpc.ServiceRegistrar, srv Mrc20HoldersServiceServer) {
	s.RegisterService(&Mrc20HoldersService_ServiceDesc, srv)
}

func _Mrc20HoldersService_FetchMrc20TickHolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mrc20TickHoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Mrc20HoldersServiceServer).FetchMrc20TickHolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mrc20HoldersService_FetchMrc20TickHolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Mrc20HoldersServiceServer).FetchMrc20TickHolders(ctx, req.(*Mrc20TickHoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mrc20HoldersService_ServiceDesc is the grpc.ServiceDesc for Mrc20HoldersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mrc20HoldersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Mrc20HoldersService",
	HandlerType: (*Mrc20HoldersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchMrc20TickHolders",
			Handler:    _Mrc20HoldersService_FetchMrc20TickHolders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mrc20_holders_service.proto",
}
