// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: mrc20_holders_service.proto

package mrc20_holders_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mrc20TickHoldersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TickId string `protobuf:"bytes,1,opt,name=tickId,proto3" json:"tickId,omitempty"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *Mrc20TickHoldersRequest) Reset() {
	*x = Mrc20TickHoldersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mrc20_holders_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mrc20TickHoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mrc20TickHoldersRequest) ProtoMessage() {}

func (x *Mrc20TickHoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mrc20_holders_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mrc20TickHoldersRequest.ProtoReflect.Descriptor instead.
func (*Mrc20TickHoldersRequest) Descriptor() ([]byte, []int) {
	return file_mrc20_holders_service_proto_rawDescGZIP(), []int{0}
}

func (x *Mrc20TickHoldersRequest) GetTickId() string {
	if x != nil {
		return x.TickId
	}
	return ""
}

func (x *Mrc20TickHoldersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Mrc20TickHoldersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Mrc20TickHoldersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int64              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Offset int64              `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Detail []*Mrc20TickHolder `protobuf:"bytes,3,rep,name=detail,proto3" json:"detail,omitempty"`
}

func (x *Mrc20TickHoldersResponse) Reset() {
	*x = Mrc20TickHoldersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mrc20_holders_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mrc20TickHoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mrc20TickHoldersResponse) ProtoMessage() {}

func (x *Mrc20TickHoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mrc20_holders_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mrc20TickHoldersResponse.ProtoReflect.Descriptor instead.
func (*Mrc20TickHoldersResponse) Descriptor() ([]byte, []int) {
	return file_mrc20_holders_service_proto_rawDescGZIP(), []int{1}
}

func (x *Mrc20TickHoldersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Mrc20TickHoldersResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Mrc20TickHoldersResponse) GetDetail() []*Mrc20TickHolder {
	if x != nil {
		return x.Detail
	}
	return nil
}

type Mrc20TickHolder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Decimal int64  `protobuf:"varint,2,opt,name=decimal,proto3" json:"decimal,omitempty"`
	Balance string `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Count   int64  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Mrc20TickHolder) Reset() {
	*x = Mrc20TickHolder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mrc20_holders_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mrc20TickHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mrc20TickHolder) ProtoMessage() {}

func (x *Mrc20TickHolder) ProtoReflect() protoreflect.Message {
	mi := &file_mrc20_holders_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mrc20TickHolder.ProtoReflect.Descriptor instead.
func (*Mrc20TickHolder) Descriptor() ([]byte, []int) {
	return file_mrc20_holders_service_proto_rawDescGZIP(), []int{2}
}

func (x *Mrc20TickHolder) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Mrc20TickHolder) GetDecimal() int64 {
	if x != nil {
		return x.Decimal
	}
	return 0
}

func (x *Mrc20TickHolder) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Mrc20TickHolder) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_mrc20_holders_service_proto protoreflect.FileDescriptor

var file_mrc20_holders_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x72, 0x63, 0x32, 0x30, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x5f, 0x0a, 0x17, 0x4d, 0x72, 0x63, 0x32, 0x30,
	0x54, 0x69, 0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x7b, 0x0a, 0x18, 0x4d, 0x72, 0x63, 0x32,
	0x30, 0x54, 0x69, 0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x72,
	0x63, 0x32, 0x30, 0x54, 0x69, 0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x75, 0x0a, 0x0f, 0x4d, 0x72, 0x63, 0x32, 0x30, 0x54, 0x69,
	0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x77, 0x0a, 0x13,
	0x4d, 0x72, 0x63, 0x32, 0x30, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x15, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x72, 0x63, 0x32,
	0x30, 0x54, 0x69, 0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x12, 0x21, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x72, 0x63, 0x32, 0x30, 0x54, 0x69, 0x63,
	0x6b, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x72, 0x63, 0x32, 0x30,
	0x54, 0x69, 0x63, 0x6b, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x6d, 0x72, 0x63, 0x32, 0x30, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mrc20_holders_service_proto_rawDescOnce sync.Once
	file_mrc20_holders_service_proto_rawDescData = file_mrc20_holders_service_proto_rawDesc
)

func file_mrc20_holders_service_proto_rawDescGZIP() []byte {
	file_mrc20_holders_service_proto_rawDescOnce.Do(func() {
		file_mrc20_holders_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_mrc20_holders_service_proto_rawDescData)
	})
	return file_mrc20_holders_service_proto_rawDescData
}

var file_mrc20_holders_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mrc20_holders_service_proto_goTypes = []interface{}{
	(*Mrc20TickHoldersRequest)(nil),  // 0: protobuf.Mrc20TickHoldersRequest
	(*Mrc20TickHoldersResponse)(nil), // 1: protobuf.Mrc20TickHoldersResponse
	(*Mrc20TickHolder)(nil),          // 2: protobuf.Mrc20TickHolder
}
var file_mrc20_holders_service_proto_depIdxs = []int32{
	2, // 0: protobuf.Mrc20TickHoldersResponse.detail:type_name -> protobuf.Mrc20TickHolder
	0, // 1: protobuf.Mrc20HoldersService.FetchMrc20TickHolders:input_type -> protobuf.Mrc20TickHoldersRequest
	1, // 2: protobuf.Mrc20HoldersService.FetchMrc20TickHolders:output_type -> protobuf.Mrc20TickHoldersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mrc20_holders_service_proto_init() }
func file_mrc20_holders_service_proto_init() {
	if File_mrc20_holders_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mrc20_holders_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mrc20TickHoldersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mrc20_holders_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mrc20TickHoldersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mrc20_holders_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mrc20TickHolder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mrc20_holders_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mrc20_holders_service_proto_goTypes,
		DependencyIndexes: file_mrc20_holders_service_proto_depIdxs,
		MessageInfos:      file_mrc20_holders_service_proto_msgTypes,
	}.Build()
	File_mrc20_holders_service_proto = out.File
	file_mrc20_holders_service_proto_rawDesc = nil
	file_mrc20_holders_service_proto_goTypes = nil
	file_mrc20_holders_service_proto_depIdxs = nil
}
