// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.3
// source: protobuf/btc_service/btc_service.proto

package btc_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchTxRawReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
}

func (x *FetchTxRawReq) Reset() {
	*x = FetchTxRawReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchTxRawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTxRawReq) ProtoMessage() {}

func (x *FetchTxRawReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTxRawReq.ProtoReflect.Descriptor instead.
func (*FetchTxRawReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{0}
}

func (x *FetchTxRawReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type FetchTxRawResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawTx string `protobuf:"bytes,1,opt,name=rawTx,proto3" json:"rawTx,omitempty"`
}

func (x *FetchTxRawResp) Reset() {
	*x = FetchTxRawResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchTxRawResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchTxRawResp) ProtoMessage() {}

func (x *FetchTxRawResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchTxRawResp.ProtoReflect.Descriptor instead.
func (*FetchTxRawResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{1}
}

func (x *FetchTxRawResp) GetRawTx() string {
	if x != nil {
		return x.RawTx
	}
	return ""
}

type CheckUtxoInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutPoints []string `protobuf:"bytes,1,rep,name=outPoints,proto3" json:"outPoints,omitempty"`
}

func (x *CheckUtxoInfoReq) Reset() {
	*x = CheckUtxoInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUtxoInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUtxoInfoReq) ProtoMessage() {}

func (x *CheckUtxoInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUtxoInfoReq.ProtoReflect.Descriptor instead.
func (*CheckUtxoInfoReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckUtxoInfoReq) GetOutPoints() []string {
	if x != nil {
		return x.OutPoints
	}
	return nil
}

type CheckUtxoInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UtxoInfos map[string]*UtxoInfo `protobuf:"bytes,1,rep,name=utxoInfos,proto3" json:"utxoInfos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CheckUtxoInfoResp) Reset() {
	*x = CheckUtxoInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckUtxoInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUtxoInfoResp) ProtoMessage() {}

func (x *CheckUtxoInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUtxoInfoResp.ProtoReflect.Descriptor instead.
func (*CheckUtxoInfoResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUtxoInfoResp) GetUtxoInfos() map[string]*UtxoInfo {
	if x != nil {
		return x.UtxoInfos
	}
	return nil
}

type UtxoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExist     bool       `protobuf:"varint,1,opt,name=isExist,proto3" json:"isExist,omitempty"`
	TxConfirm   bool       `protobuf:"varint,2,opt,name=txConfirm,proto3" json:"txConfirm,omitempty"`
	SpendStatus string     `protobuf:"bytes,3,opt,name=spendStatus,proto3" json:"spendStatus,omitempty"`
	Height      int64      `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Date        int64      `protobuf:"varint,5,opt,name=date,proto3" json:"date,omitempty"`
	Value       int64      `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	Where       string     `protobuf:"bytes,7,opt,name=where,proto3" json:"where,omitempty"`
	Address     string     `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	SpendInfo   *SpendInfo `protobuf:"bytes,9,opt,name=spendInfo,proto3" json:"spendInfo,omitempty"`
}

func (x *UtxoInfo) Reset() {
	*x = UtxoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UtxoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoInfo) ProtoMessage() {}

func (x *UtxoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoInfo.ProtoReflect.Descriptor instead.
func (*UtxoInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{4}
}

func (x *UtxoInfo) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

func (x *UtxoInfo) GetTxConfirm() bool {
	if x != nil {
		return x.TxConfirm
	}
	return false
}

func (x *UtxoInfo) GetSpendStatus() string {
	if x != nil {
		return x.SpendStatus
	}
	return ""
}

func (x *UtxoInfo) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UtxoInfo) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *UtxoInfo) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *UtxoInfo) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *UtxoInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UtxoInfo) GetSpendInfo() *SpendInfo {
	if x != nil {
		return x.SpendInfo
	}
	return nil
}

type SpendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpendTx string `protobuf:"bytes,1,opt,name=spendTx,proto3" json:"spendTx,omitempty"`
	Height  int64  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Date    int64  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Where   string `protobuf:"bytes,4,opt,name=where,proto3" json:"where,omitempty"`
}

func (x *SpendInfo) Reset() {
	*x = SpendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendInfo) ProtoMessage() {}

func (x *SpendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendInfo.ProtoReflect.Descriptor instead.
func (*SpendInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{5}
}

func (x *SpendInfo) GetSpendTx() string {
	if x != nil {
		return x.SpendTx
	}
	return ""
}

func (x *SpendInfo) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SpendInfo) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *SpendInfo) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

type BtcBroadcastTxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawTx string `protobuf:"bytes,1,opt,name=rawTx,proto3" json:"rawTx,omitempty"`
}

func (x *BtcBroadcastTxReq) Reset() {
	*x = BtcBroadcastTxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcBroadcastTxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcBroadcastTxReq) ProtoMessage() {}

func (x *BtcBroadcastTxReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcBroadcastTxReq.ProtoReflect.Descriptor instead.
func (*BtcBroadcastTxReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{6}
}

func (x *BtcBroadcastTxReq) GetRawTx() string {
	if x != nil {
		return x.RawTx
	}
	return ""
}

type BtcBroadcastTxResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId    string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BtcBroadcastTxResp) Reset() {
	*x = BtcBroadcastTxResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcBroadcastTxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcBroadcastTxResp) ProtoMessage() {}

func (x *BtcBroadcastTxResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcBroadcastTxResp.ProtoReflect.Descriptor instead.
func (*BtcBroadcastTxResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{7}
}

func (x *BtcBroadcastTxResp) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *BtcBroadcastTxResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BtcCheckTxInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
}

func (x *BtcCheckTxInfoReq) Reset() {
	*x = BtcCheckTxInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcCheckTxInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcCheckTxInfoReq) ProtoMessage() {}

func (x *BtcCheckTxInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcCheckTxInfoReq.ProtoReflect.Descriptor instead.
func (*BtcCheckTxInfoReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{8}
}

func (x *BtcCheckTxInfoReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type BtcCheckTxInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash    string   `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Address   []string `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Value     []int64  `protobuf:"varint,3,rep,packed,name=value,proto3" json:"value,omitempty"`
	Input     []string `protobuf:"bytes,4,rep,name=input,proto3" json:"input,omitempty"`
	Height    int64    `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Date      int64    `protobuf:"varint,6,opt,name=date,proto3" json:"date,omitempty"`
	Confirmed bool     `protobuf:"varint,7,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
}

func (x *BtcCheckTxInfoResp) Reset() {
	*x = BtcCheckTxInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcCheckTxInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcCheckTxInfoResp) ProtoMessage() {}

func (x *BtcCheckTxInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcCheckTxInfoResp.ProtoReflect.Descriptor instead.
func (*BtcCheckTxInfoResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{9}
}

func (x *BtcCheckTxInfoResp) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *BtcCheckTxInfoResp) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *BtcCheckTxInfoResp) GetValue() []int64 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BtcCheckTxInfoResp) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *BtcCheckTxInfoResp) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BtcCheckTxInfoResp) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *BtcCheckTxInfoResp) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

type FetchBtcUtxoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Order       string `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Unconfirmed string `protobuf:"bytes,3,opt,name=unconfirmed,proto3" json:"unconfirmed,omitempty"`
}

func (x *FetchBtcUtxoReq) Reset() {
	*x = FetchBtcUtxoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchBtcUtxoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBtcUtxoReq) ProtoMessage() {}

func (x *FetchBtcUtxoReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBtcUtxoReq.ProtoReflect.Descriptor instead.
func (*FetchBtcUtxoReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{10}
}

func (x *FetchBtcUtxoReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FetchBtcUtxoReq) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *FetchBtcUtxoReq) GetUnconfirmed() string {
	if x != nil {
		return x.Unconfirmed
	}
	return ""
}

type FetchBtcUtxoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Utxos []*FetchUtxoItem `protobuf:"bytes,1,rep,name=utxos,proto3" json:"utxos,omitempty"`
}

func (x *FetchBtcUtxoResp) Reset() {
	*x = FetchBtcUtxoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchBtcUtxoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBtcUtxoResp) ProtoMessage() {}

func (x *FetchBtcUtxoResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBtcUtxoResp.ProtoReflect.Descriptor instead.
func (*FetchBtcUtxoResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{11}
}

func (x *FetchBtcUtxoResp) GetUtxos() []*FetchUtxoItem {
	if x != nil {
		return x.Utxos
	}
	return nil
}

type FetchUtxoItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confirmed    bool   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Inscriptions string `protobuf:"bytes,2,opt,name=inscriptions,proto3" json:"inscriptions,omitempty"`
	Satoshi      int64  `protobuf:"varint,3,opt,name=satoshi,proto3" json:"satoshi,omitempty"`
	TxId         string `protobuf:"bytes,4,opt,name=txId,proto3" json:"txId,omitempty"`
	Vout         int64  `protobuf:"varint,5,opt,name=vout,proto3" json:"vout,omitempty"`
	OutputIndex  int64  `protobuf:"varint,6,opt,name=outputIndex,proto3" json:"outputIndex,omitempty"`
	Satoshis     int64  `protobuf:"varint,7,opt,name=satoshis,proto3" json:"satoshis,omitempty"`
}

func (x *FetchUtxoItem) Reset() {
	*x = FetchUtxoItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchUtxoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUtxoItem) ProtoMessage() {}

func (x *FetchUtxoItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUtxoItem.ProtoReflect.Descriptor instead.
func (*FetchUtxoItem) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{12}
}

func (x *FetchUtxoItem) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *FetchUtxoItem) GetInscriptions() string {
	if x != nil {
		return x.Inscriptions
	}
	return ""
}

func (x *FetchUtxoItem) GetSatoshi() int64 {
	if x != nil {
		return x.Satoshi
	}
	return 0
}

func (x *FetchUtxoItem) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *FetchUtxoItem) GetVout() int64 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *FetchUtxoItem) GetOutputIndex() int64 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

func (x *FetchUtxoItem) GetSatoshis() int64 {
	if x != nil {
		return x.Satoshis
	}
	return 0
}

type FetchBtcBalanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *FetchBtcBalanceReq) Reset() {
	*x = FetchBtcBalanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchBtcBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBtcBalanceReq) ProtoMessage() {}

func (x *FetchBtcBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBtcBalanceReq.ProtoReflect.Descriptor instead.
func (*FetchBtcBalanceReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{13}
}

func (x *FetchBtcBalanceReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type FetchBtcBalanceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSatoshi              int64 `protobuf:"varint,1,opt,name=totalSatoshi,proto3" json:"totalSatoshi,omitempty"`
	BtcSatoshi                int64 `protobuf:"varint,2,opt,name=btcSatoshi,proto3" json:"btcSatoshi,omitempty"`
	BtcPendingSatoshi         int64 `protobuf:"varint,3,opt,name=btcPendingSatoshi,proto3" json:"btcPendingSatoshi,omitempty"`
	InscriptionSatoshi        int64 `protobuf:"varint,4,opt,name=inscriptionSatoshi,proto3" json:"inscriptionSatoshi,omitempty"`
	InscriptionPendingSatoshi int64 `protobuf:"varint,5,opt,name=inscriptionPendingSatoshi,proto3" json:"inscriptionPendingSatoshi,omitempty"`
	PinSatoshi                int64 `protobuf:"varint,6,opt,name=pinSatoshi,proto3" json:"pinSatoshi,omitempty"`
	PinPendingSatoshi         int64 `protobuf:"varint,7,opt,name=pinPendingSatoshi,proto3" json:"pinPendingSatoshi,omitempty"`
	Mrc20Satoshi              int64 `protobuf:"varint,8,opt,name=mrc20Satoshi,proto3" json:"mrc20Satoshi,omitempty"`
	Mrc20PendingSatoshi       int64 `protobuf:"varint,9,opt,name=mrc20PendingSatoshi,proto3" json:"mrc20PendingSatoshi,omitempty"`
	RuneSatoshi               int64 `protobuf:"varint,10,opt,name=runeSatoshi,proto3" json:"runeSatoshi,omitempty"`
	RunePendingSatoshi        int64 `protobuf:"varint,11,opt,name=runePendingSatoshi,proto3" json:"runePendingSatoshi,omitempty"`
}

func (x *FetchBtcBalanceResp) Reset() {
	*x = FetchBtcBalanceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchBtcBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBtcBalanceResp) ProtoMessage() {}

func (x *FetchBtcBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBtcBalanceResp.ProtoReflect.Descriptor instead.
func (*FetchBtcBalanceResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{14}
}

func (x *FetchBtcBalanceResp) GetTotalSatoshi() int64 {
	if x != nil {
		return x.TotalSatoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetBtcSatoshi() int64 {
	if x != nil {
		return x.BtcSatoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetBtcPendingSatoshi() int64 {
	if x != nil {
		return x.BtcPendingSatoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetInscriptionSatoshi() int64 {
	if x != nil {
		return x.InscriptionSatoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetInscriptionPendingSatoshi() int64 {
	if x != nil {
		return x.InscriptionPendingSatoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetPinSatoshi() int64 {
	if x != nil {
		return x.PinSatoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetPinPendingSatoshi() int64 {
	if x != nil {
		return x.PinPendingSatoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetMrc20Satoshi() int64 {
	if x != nil {
		return x.Mrc20Satoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetMrc20PendingSatoshi() int64 {
	if x != nil {
		return x.Mrc20PendingSatoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetRuneSatoshi() int64 {
	if x != nil {
		return x.RuneSatoshi
	}
	return 0
}

func (x *FetchBtcBalanceResp) GetRunePendingSatoshi() int64 {
	if x != nil {
		return x.RunePendingSatoshi
	}
	return 0
}

// New BTC APIs (aligned with Doge semantics)
type BtcAddressBalanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Source  string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *BtcAddressBalanceReq) Reset() {
	*x = BtcAddressBalanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcAddressBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcAddressBalanceReq) ProtoMessage() {}

func (x *BtcAddressBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcAddressBalanceReq.ProtoReflect.Descriptor instead.
func (*BtcAddressBalanceReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{15}
}

func (x *BtcAddressBalanceReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BtcAddressBalanceReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type BtcAddressBalanceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Confirmed   uint64 `protobuf:"varint,2,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Unconfirmed int64  `protobuf:"varint,3,opt,name=unconfirmed,proto3" json:"unconfirmed,omitempty"`
	UtxoCount   int32  `protobuf:"varint,4,opt,name=utxoCount,proto3" json:"utxoCount,omitempty"`
}

func (x *BtcAddressBalanceResp) Reset() {
	*x = BtcAddressBalanceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcAddressBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcAddressBalanceResp) ProtoMessage() {}

func (x *BtcAddressBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcAddressBalanceResp.ProtoReflect.Descriptor instead.
func (*BtcAddressBalanceResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{16}
}

func (x *BtcAddressBalanceResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BtcAddressBalanceResp) GetConfirmed() uint64 {
	if x != nil {
		return x.Confirmed
	}
	return 0
}

func (x *BtcAddressBalanceResp) GetUnconfirmed() int64 {
	if x != nil {
		return x.Unconfirmed
	}
	return 0
}

func (x *BtcAddressBalanceResp) GetUtxoCount() int32 {
	if x != nil {
		return x.UtxoCount
	}
	return 0
}

type BtcAddressUtxoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Flag    string `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Source  string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *BtcAddressUtxoReq) Reset() {
	*x = BtcAddressUtxoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcAddressUtxoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcAddressUtxoReq) ProtoMessage() {}

func (x *BtcAddressUtxoReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcAddressUtxoReq.ProtoReflect.Descriptor instead.
func (*BtcAddressUtxoReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{17}
}

func (x *BtcAddressUtxoReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BtcAddressUtxoReq) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *BtcAddressUtxoReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type BtcAddressUtxoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Utxos []*BtcUtxo `protobuf:"bytes,1,rep,name=utxos,proto3" json:"utxos,omitempty"`
	Total int64      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *BtcAddressUtxoResp) Reset() {
	*x = BtcAddressUtxoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcAddressUtxoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcAddressUtxoResp) ProtoMessage() {}

func (x *BtcAddressUtxoResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcAddressUtxoResp.ProtoReflect.Descriptor instead.
func (*BtcAddressUtxoResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{18}
}

func (x *BtcAddressUtxoResp) GetUtxos() []*BtcUtxo {
	if x != nil {
		return x.Utxos
	}
	return nil
}

func (x *BtcAddressUtxoResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BtcUtxo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag     string `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Txid     string `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	OutIndex int32  `protobuf:"varint,3,opt,name=outIndex,proto3" json:"outIndex,omitempty"`
	Value    string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Height   int64  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Address  string `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *BtcUtxo) Reset() {
	*x = BtcUtxo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcUtxo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcUtxo) ProtoMessage() {}

func (x *BtcUtxo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcUtxo.ProtoReflect.Descriptor instead.
func (*BtcUtxo) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{19}
}

func (x *BtcUtxo) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *BtcUtxo) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *BtcUtxo) GetOutIndex() int32 {
	if x != nil {
		return x.OutIndex
	}
	return 0
}

func (x *BtcUtxo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BtcUtxo) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BtcUtxo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type BtcAddressTxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Limit     int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Flag      string `protobuf:"bytes,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Confirmed bool   `protobuf:"varint,4,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Source    string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *BtcAddressTxReq) Reset() {
	*x = BtcAddressTxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcAddressTxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcAddressTxReq) ProtoMessage() {}

func (x *BtcAddressTxReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcAddressTxReq.ProtoReflect.Descriptor instead.
func (*BtcAddressTxReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{20}
}

func (x *BtcAddressTxReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BtcAddressTxReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BtcAddressTxReq) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *BtcAddressTxReq) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *BtcAddressTxReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type BtcAddressTxResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txs   []*BtcAddressTx `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	Total int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *BtcAddressTxResp) Reset() {
	*x = BtcAddressTxResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcAddressTxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcAddressTxResp) ProtoMessage() {}

func (x *BtcAddressTxResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcAddressTxResp.ProtoReflect.Descriptor instead.
func (*BtcAddressTxResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{21}
}

func (x *BtcAddressTxResp) GetTxs() []*BtcAddressTx {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *BtcAddressTxResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BtcAddressTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid     string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Time     int64  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Height   int64  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Address  string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Flag     string `protobuf:"bytes,5,opt,name=flag,proto3" json:"flag,omitempty"`
	Income   int64  `protobuf:"varint,6,opt,name=income,proto3" json:"income,omitempty"`
	Outcome  int64  `protobuf:"varint,7,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Genesis  string `protobuf:"bytes,8,opt,name=genesis,proto3" json:"genesis,omitempty"`
	CreateAt string `protobuf:"bytes,9,opt,name=createAt,proto3" json:"createAt,omitempty"`
}

func (x *BtcAddressTx) Reset() {
	*x = BtcAddressTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcAddressTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcAddressTx) ProtoMessage() {}

func (x *BtcAddressTx) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcAddressTx.ProtoReflect.Descriptor instead.
func (*BtcAddressTx) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{22}
}

func (x *BtcAddressTx) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *BtcAddressTx) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BtcAddressTx) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BtcAddressTx) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BtcAddressTx) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *BtcAddressTx) GetIncome() int64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *BtcAddressTx) GetOutcome() int64 {
	if x != nil {
		return x.Outcome
	}
	return 0
}

func (x *BtcAddressTx) GetGenesis() string {
	if x != nil {
		return x.Genesis
	}
	return ""
}

func (x *BtcAddressTx) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type BtcAddressTxCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Source  string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *BtcAddressTxCountReq) Reset() {
	*x = BtcAddressTxCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcAddressTxCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcAddressTxCountReq) ProtoMessage() {}

func (x *BtcAddressTxCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcAddressTxCountReq.ProtoReflect.Descriptor instead.
func (*BtcAddressTxCountReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{23}
}

func (x *BtcAddressTxCountReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BtcAddressTxCountReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type BtcAddressTxCountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxCount int64 `protobuf:"varint,1,opt,name=txCount,proto3" json:"txCount,omitempty"`
}

func (x *BtcAddressTxCountResp) Reset() {
	*x = BtcAddressTxCountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcAddressTxCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcAddressTxCountResp) ProtoMessage() {}

func (x *BtcAddressTxCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcAddressTxCountResp.ProtoReflect.Descriptor instead.
func (*BtcAddressTxCountResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{24}
}

func (x *BtcAddressTxCountResp) GetTxCount() int64 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

type BtcTxRawReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId   string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *BtcTxRawReq) Reset() {
	*x = BtcTxRawReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcTxRawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcTxRawReq) ProtoMessage() {}

func (x *BtcTxRawReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcTxRawReq.ProtoReflect.Descriptor instead.
func (*BtcTxRawReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{25}
}

func (x *BtcTxRawReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *BtcTxRawReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type BtcTxRawResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxRaw string `protobuf:"bytes,1,opt,name=txRaw,proto3" json:"txRaw,omitempty"`
}

func (x *BtcTxRawResp) Reset() {
	*x = BtcTxRawResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcTxRawResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcTxRawResp) ProtoMessage() {}

func (x *BtcTxRawResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcTxRawResp.ProtoReflect.Descriptor instead.
func (*BtcTxRawResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{26}
}

func (x *BtcTxRawResp) GetTxRaw() string {
	if x != nil {
		return x.TxRaw
	}
	return ""
}

type BtcFeeRateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BtcFeeRateReq) Reset() {
	*x = BtcFeeRateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcFeeRateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcFeeRateReq) ProtoMessage() {}

func (x *BtcFeeRateReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcFeeRateReq.ProtoReflect.Descriptor instead.
func (*BtcFeeRateReq) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{27}
}

type BtcFeeRateItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc    string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	FeeRate int64  `protobuf:"varint,3,opt,name=feeRate,proto3" json:"feeRate,omitempty"`
}

func (x *BtcFeeRateItem) Reset() {
	*x = BtcFeeRateItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcFeeRateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcFeeRateItem) ProtoMessage() {}

func (x *BtcFeeRateItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcFeeRateItem.ProtoReflect.Descriptor instead.
func (*BtcFeeRateItem) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{28}
}

func (x *BtcFeeRateItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BtcFeeRateItem) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *BtcFeeRateItem) GetFeeRate() int64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

type BtcFeeRateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*BtcFeeRateItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *BtcFeeRateResp) Reset() {
	*x = BtcFeeRateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcFeeRateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcFeeRateResp) ProtoMessage() {}

func (x *BtcFeeRateResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_btc_service_btc_service_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcFeeRateResp.ProtoReflect.Descriptor instead.
func (*BtcFeeRateResp) Descriptor() ([]byte, []int) {
	return file_protobuf_btc_service_btc_service_proto_rawDescGZIP(), []int{29}
}

func (x *BtcFeeRateResp) GetList() []*BtcFeeRateItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_protobuf_btc_service_btc_service_proto protoreflect.FileDescriptor

var file_protobuf_btc_service_btc_service_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x74, 0x63, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x74, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x23, 0x0a, 0x0d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x78, 0x52, 0x61, 0x77,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x54, 0x78, 0x52, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x77,
	0x54, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61, 0x77, 0x54, 0x78, 0x22,
	0x30, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x74, 0x78, 0x6f, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x22, 0xaf, 0x01, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x74, 0x78, 0x6f, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x09, 0x75, 0x74, 0x78, 0x6f, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x74, 0x78, 0x6f, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x55, 0x74, 0x78, 0x6f, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x75, 0x74, 0x78, 0x6f, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x1a, 0x50, 0x0a, 0x0e, 0x55, 0x74, 0x78, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x55, 0x74, 0x78, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x89, 0x02, 0x0a, 0x08, 0x55, 0x74, 0x78, 0x6f, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x78,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x74,
	0x78, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x70, 0x65, 0x6e,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x70, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x68, 0x65, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x68, 0x65,
	0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x31, 0x0a, 0x09,
	0x73, 0x70, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x70, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x67, 0x0a, 0x09, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x70, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x70, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x77, 0x68, 0x65, 0x72, 0x65, 0x22, 0x29, 0x0a, 0x11, 0x42, 0x74, 0x63, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54, 0x78, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x61, 0x77, 0x54, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61,
	0x77, 0x54, 0x78, 0x22, 0x42, 0x0a, 0x12, 0x42, 0x74, 0x63, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x42, 0x74, 0x63, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x54, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64,
	0x22, 0xbc, 0x01, 0x0a, 0x12, 0x42, 0x74, 0x63, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x78, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x22,
	0x63, 0x0a, 0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x74, 0x63, 0x55, 0x74, 0x78, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x65, 0x64, 0x22, 0x41, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x74, 0x63,
	0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x05, 0x75, 0x74, 0x78, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x74, 0x78, 0x6f, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x75, 0x74, 0x78, 0x6f, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x0d, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x55, 0x74, 0x78, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69,
	0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x61,
	0x74, 0x6f, 0x73, 0x68, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x75,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x76, 0x6f, 0x75, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x73, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x73, 0x22, 0x2e, 0x0a, 0x12, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x42, 0x74, 0x63, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xeb, 0x03, 0x0a, 0x13,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x74, 0x63, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x61, 0x74, 0x6f,
	0x73, 0x68, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x74, 0x63, 0x53, 0x61,
	0x74, 0x6f, 0x73, 0x68, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x74, 0x63,
	0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x12, 0x2c, 0x0a, 0x11, 0x62, 0x74, 0x63, 0x50, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x11, 0x62, 0x74, 0x63, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x61,
	0x74, 0x6f, 0x73, 0x68, 0x69, 0x12, 0x2e, 0x0a, 0x12, 0x69, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x12, 0x69, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x61,
	0x74, 0x6f, 0x73, 0x68, 0x69, 0x12, 0x3c, 0x0a, 0x19, 0x69, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x61, 0x74, 0x6f, 0x73,
	0x68, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x19, 0x69, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x61, 0x74, 0x6f,
	0x73, 0x68, 0x69, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x69, 0x6e, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68,
	0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x69, 0x6e, 0x53, 0x61, 0x74, 0x6f,
	0x73, 0x68, 0x69, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x69, 0x6e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11,
	0x70, 0x69, 0x6e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68,
	0x69, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x72, 0x63, 0x32, 0x30, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68,
	0x69, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x72, 0x63, 0x32, 0x30, 0x53, 0x61,
	0x74, 0x6f, 0x73, 0x68, 0x69, 0x12, 0x30, 0x0a, 0x13, 0x6d, 0x72, 0x63, 0x32, 0x30, 0x50, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x13, 0x6d, 0x72, 0x63, 0x32, 0x30, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x75, 0x6e, 0x65, 0x53,
	0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x75,
	0x6e, 0x65, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x12, 0x2e, 0x0a, 0x12, 0x72, 0x75, 0x6e,
	0x65, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x72, 0x75, 0x6e, 0x65, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x53, 0x61, 0x74, 0x6f, 0x73, 0x68, 0x69, 0x22, 0x48, 0x0a, 0x14, 0x42, 0x74, 0x63,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x15, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x6e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x74, 0x78, 0x6f, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x74, 0x78, 0x6f,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x59, 0x0a, 0x11, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x22, 0x53, 0x0a, 0x12, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x55, 0x74,
	0x78, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x05, 0x75, 0x74, 0x78, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x42, 0x74, 0x63, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x05, 0x75, 0x74, 0x78, 0x6f, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x95, 0x01, 0x0a, 0x07, 0x42, 0x74, 0x63, 0x55, 0x74, 0x78,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x75, 0x74,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x75, 0x74,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x8b, 0x01,
	0x0a, 0x0f, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x78, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x52, 0x0a, 0x10, 0x42,
	0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x28, 0x0a, 0x03, 0x74, 0x78, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x54, 0x78, 0x52, 0x03, 0x74, 0x78, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0xe4, 0x01, 0x0a, 0x0c, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x78, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x48, 0x0a, 0x14, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x54, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x22, 0x31, 0x0a, 0x15, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x78,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x78, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x39, 0x0a, 0x0b, 0x42, 0x74, 0x63, 0x54, 0x78, 0x52, 0x61, 0x77, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x24,
	0x0a, 0x0c, 0x42, 0x74, 0x63, 0x54, 0x78, 0x52, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x78, 0x52, 0x61, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x78, 0x52, 0x61, 0x77, 0x22, 0x0f, 0x0a, 0x0d, 0x42, 0x74, 0x63, 0x46, 0x65, 0x65, 0x52, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x22, 0x54, 0x0a, 0x0e, 0x42, 0x74, 0x63, 0x46, 0x65, 0x65, 0x52,
	0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x66, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x42,
	0x74, 0x63, 0x46, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x46, 0x65, 0x65, 0x52, 0x61, 0x74,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xae, 0x07, 0x0a, 0x0a,
	0x42, 0x74, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x55, 0x74, 0x78, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x74, 0x78, 0x6f,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x74, 0x78, 0x6f, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54,
	0x78, 0x52, 0x61, 0x77, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x78, 0x52, 0x61, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x54, 0x78,
	0x52, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x42, 0x74, 0x63,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54, 0x78, 0x12, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x54, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x42, 0x74, 0x63, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x54, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x78,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x78, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x42, 0x74, 0x63, 0x55, 0x74, 0x78, 0x6f, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x74, 0x63, 0x55, 0x74, 0x78, 0x6f, 0x52,
	0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x42, 0x74, 0x63, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x50, 0x0a, 0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x74, 0x63, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x42, 0x74, 0x63, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x42, 0x74, 0x63, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x59, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x50, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x55, 0x74,
	0x78, 0x6f, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74,
	0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x54, 0x78, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74,
	0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x42, 0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x78, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42,
	0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42,
	0x74, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x74, 0x63,
	0x54, 0x78, 0x52, 0x61, 0x77, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x42, 0x74, 0x63, 0x54, 0x78, 0x52, 0x61, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x54, 0x78, 0x52, 0x61, 0x77,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x74, 0x63,
	0x46, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x46, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x74, 0x63, 0x46,
	0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x74, 0x63, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_btc_service_btc_service_proto_rawDescOnce sync.Once
	file_protobuf_btc_service_btc_service_proto_rawDescData = file_protobuf_btc_service_btc_service_proto_rawDesc
)

func file_protobuf_btc_service_btc_service_proto_rawDescGZIP() []byte {
	file_protobuf_btc_service_btc_service_proto_rawDescOnce.Do(func() {
		file_protobuf_btc_service_btc_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_btc_service_btc_service_proto_rawDescData)
	})
	return file_protobuf_btc_service_btc_service_proto_rawDescData
}

var file_protobuf_btc_service_btc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_protobuf_btc_service_btc_service_proto_goTypes = []interface{}{
	(*FetchTxRawReq)(nil),         // 0: protobuf.FetchTxRawReq
	(*FetchTxRawResp)(nil),        // 1: protobuf.FetchTxRawResp
	(*CheckUtxoInfoReq)(nil),      // 2: protobuf.CheckUtxoInfoReq
	(*CheckUtxoInfoResp)(nil),     // 3: protobuf.CheckUtxoInfoResp
	(*UtxoInfo)(nil),              // 4: protobuf.UtxoInfo
	(*SpendInfo)(nil),             // 5: protobuf.SpendInfo
	(*BtcBroadcastTxReq)(nil),     // 6: protobuf.BtcBroadcastTxReq
	(*BtcBroadcastTxResp)(nil),    // 7: protobuf.BtcBroadcastTxResp
	(*BtcCheckTxInfoReq)(nil),     // 8: protobuf.BtcCheckTxInfoReq
	(*BtcCheckTxInfoResp)(nil),    // 9: protobuf.BtcCheckTxInfoResp
	(*FetchBtcUtxoReq)(nil),       // 10: protobuf.FetchBtcUtxoReq
	(*FetchBtcUtxoResp)(nil),      // 11: protobuf.FetchBtcUtxoResp
	(*FetchUtxoItem)(nil),         // 12: protobuf.FetchUtxoItem
	(*FetchBtcBalanceReq)(nil),    // 13: protobuf.FetchBtcBalanceReq
	(*FetchBtcBalanceResp)(nil),   // 14: protobuf.FetchBtcBalanceResp
	(*BtcAddressBalanceReq)(nil),  // 15: protobuf.BtcAddressBalanceReq
	(*BtcAddressBalanceResp)(nil), // 16: protobuf.BtcAddressBalanceResp
	(*BtcAddressUtxoReq)(nil),     // 17: protobuf.BtcAddressUtxoReq
	(*BtcAddressUtxoResp)(nil),    // 18: protobuf.BtcAddressUtxoResp
	(*BtcUtxo)(nil),               // 19: protobuf.BtcUtxo
	(*BtcAddressTxReq)(nil),       // 20: protobuf.BtcAddressTxReq
	(*BtcAddressTxResp)(nil),      // 21: protobuf.BtcAddressTxResp
	(*BtcAddressTx)(nil),          // 22: protobuf.BtcAddressTx
	(*BtcAddressTxCountReq)(nil),  // 23: protobuf.BtcAddressTxCountReq
	(*BtcAddressTxCountResp)(nil), // 24: protobuf.BtcAddressTxCountResp
	(*BtcTxRawReq)(nil),           // 25: protobuf.BtcTxRawReq
	(*BtcTxRawResp)(nil),          // 26: protobuf.BtcTxRawResp
	(*BtcFeeRateReq)(nil),         // 27: protobuf.BtcFeeRateReq
	(*BtcFeeRateItem)(nil),        // 28: protobuf.BtcFeeRateItem
	(*BtcFeeRateResp)(nil),        // 29: protobuf.BtcFeeRateResp
	nil,                           // 30: protobuf.CheckUtxoInfoResp.UtxoInfosEntry
}
var file_protobuf_btc_service_btc_service_proto_depIdxs = []int32{
	30, // 0: protobuf.CheckUtxoInfoResp.utxoInfos:type_name -> protobuf.CheckUtxoInfoResp.UtxoInfosEntry
	5,  // 1: protobuf.UtxoInfo.spendInfo:type_name -> protobuf.SpendInfo
	12, // 2: protobuf.FetchBtcUtxoResp.utxos:type_name -> protobuf.FetchUtxoItem
	19, // 3: protobuf.BtcAddressUtxoResp.utxos:type_name -> protobuf.BtcUtxo
	22, // 4: protobuf.BtcAddressTxResp.txs:type_name -> protobuf.BtcAddressTx
	28, // 5: protobuf.BtcFeeRateResp.list:type_name -> protobuf.BtcFeeRateItem
	4,  // 6: protobuf.CheckUtxoInfoResp.UtxoInfosEntry.value:type_name -> protobuf.UtxoInfo
	2,  // 7: protobuf.BtcService.CheckUtxoInfo:input_type -> protobuf.CheckUtxoInfoReq
	0,  // 8: protobuf.BtcService.FetchTxRaw:input_type -> protobuf.FetchTxRawReq
	6,  // 9: protobuf.BtcService.BtcBroadcastTx:input_type -> protobuf.BtcBroadcastTxReq
	8,  // 10: protobuf.BtcService.BtcCheckTxInfo:input_type -> protobuf.BtcCheckTxInfoReq
	10, // 11: protobuf.BtcService.FetchBtcUtxo:input_type -> protobuf.FetchBtcUtxoReq
	13, // 12: protobuf.BtcService.FetchBtcBalance:input_type -> protobuf.FetchBtcBalanceReq
	15, // 13: protobuf.BtcService.GetBtcAddressBalance:input_type -> protobuf.BtcAddressBalanceReq
	17, // 14: protobuf.BtcService.GetBtcAddressUtxo:input_type -> protobuf.BtcAddressUtxoReq
	20, // 15: protobuf.BtcService.GetBtcAddressTx:input_type -> protobuf.BtcAddressTxReq
	23, // 16: protobuf.BtcService.GetBtcAddressTxCount:input_type -> protobuf.BtcAddressTxCountReq
	25, // 17: protobuf.BtcService.GetBtcTxRaw:input_type -> protobuf.BtcTxRawReq
	27, // 18: protobuf.BtcService.GetBtcFeeRate:input_type -> protobuf.BtcFeeRateReq
	3,  // 19: protobuf.BtcService.CheckUtxoInfo:output_type -> protobuf.CheckUtxoInfoResp
	1,  // 20: protobuf.BtcService.FetchTxRaw:output_type -> protobuf.FetchTxRawResp
	7,  // 21: protobuf.BtcService.BtcBroadcastTx:output_type -> protobuf.BtcBroadcastTxResp
	9,  // 22: protobuf.BtcService.BtcCheckTxInfo:output_type -> protobuf.BtcCheckTxInfoResp
	11, // 23: protobuf.BtcService.FetchBtcUtxo:output_type -> protobuf.FetchBtcUtxoResp
	14, // 24: protobuf.BtcService.FetchBtcBalance:output_type -> protobuf.FetchBtcBalanceResp
	16, // 25: protobuf.BtcService.GetBtcAddressBalance:output_type -> protobuf.BtcAddressBalanceResp
	18, // 26: protobuf.BtcService.GetBtcAddressUtxo:output_type -> protobuf.BtcAddressUtxoResp
	21, // 27: protobuf.BtcService.GetBtcAddressTx:output_type -> protobuf.BtcAddressTxResp
	24, // 28: protobuf.BtcService.GetBtcAddressTxCount:output_type -> protobuf.BtcAddressTxCountResp
	26, // 29: protobuf.BtcService.GetBtcTxRaw:output_type -> protobuf.BtcTxRawResp
	29, // 30: protobuf.BtcService.GetBtcFeeRate:output_type -> protobuf.BtcFeeRateResp
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_btc_service_btc_service_proto_init() }
func file_protobuf_btc_service_btc_service_proto_init() {
	if File_protobuf_btc_service_btc_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_btc_service_btc_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchTxRawReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchTxRawResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUtxoInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckUtxoInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UtxoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcBroadcastTxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcBroadcastTxResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcCheckTxInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcCheckTxInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchBtcUtxoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchBtcUtxoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchUtxoItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchBtcBalanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchBtcBalanceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcAddressBalanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcAddressBalanceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcAddressUtxoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcAddressUtxoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcUtxo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcAddressTxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcAddressTxResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcAddressTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcAddressTxCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcAddressTxCountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcTxRawReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcTxRawResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcFeeRateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcFeeRateItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_btc_service_btc_service_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcFeeRateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_btc_service_btc_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_btc_service_btc_service_proto_goTypes,
		DependencyIndexes: file_protobuf_btc_service_btc_service_proto_depIdxs,
		MessageInfos:      file_protobuf_btc_service_btc_service_proto_msgTypes,
	}.Build()
	File_protobuf_btc_service_btc_service_proto = out.File
	file_protobuf_btc_service_btc_service_proto_rawDesc = nil
	file_protobuf_btc_service_btc_service_proto_goTypes = nil
	file_protobuf_btc_service_btc_service_proto_depIdxs = nil
}
