// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: protobuf/btc_service/btc_service.proto

package btc_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BtcService_CheckUtxoInfo_FullMethodName        = "/protobuf.BtcService/CheckUtxoInfo"
	BtcService_FetchTxRaw_FullMethodName           = "/protobuf.BtcService/FetchTxRaw"
	BtcService_BtcBroadcastTx_FullMethodName       = "/protobuf.BtcService/BtcBroadcastTx"
	BtcService_BtcCheckTxInfo_FullMethodName       = "/protobuf.BtcService/BtcCheckTxInfo"
	BtcService_FetchBtcUtxo_FullMethodName         = "/protobuf.BtcService/FetchBtcUtxo"
	BtcService_FetchBtcBalance_FullMethodName      = "/protobuf.BtcService/FetchBtcBalance"
	BtcService_GetBtcAddressBalance_FullMethodName = "/protobuf.BtcService/GetBtcAddressBalance"
	BtcService_GetBtcAddressUtxo_FullMethodName    = "/protobuf.BtcService/GetBtcAddressUtxo"
	BtcService_GetBtcAddressTx_FullMethodName      = "/protobuf.BtcService/GetBtcAddressTx"
	BtcService_GetBtcAddressTxCount_FullMethodName = "/protobuf.BtcService/GetBtcAddressTxCount"
	BtcService_GetBtcTxRaw_FullMethodName          = "/protobuf.BtcService/GetBtcTxRaw"
	BtcService_GetBtcFeeRate_FullMethodName        = "/protobuf.BtcService/GetBtcFeeRate"
)

// BtcServiceClient is the client API for BtcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BtcServiceClient interface {
	CheckUtxoInfo(ctx context.Context, in *CheckUtxoInfoReq, opts ...grpc.CallOption) (*CheckUtxoInfoResp, error)
	FetchTxRaw(ctx context.Context, in *FetchTxRawReq, opts ...grpc.CallOption) (*FetchTxRawResp, error)
	BtcBroadcastTx(ctx context.Context, in *BtcBroadcastTxReq, opts ...grpc.CallOption) (*BtcBroadcastTxResp, error)
	BtcCheckTxInfo(ctx context.Context, in *BtcCheckTxInfoReq, opts ...grpc.CallOption) (*BtcCheckTxInfoResp, error)
	FetchBtcUtxo(ctx context.Context, in *FetchBtcUtxoReq, opts ...grpc.CallOption) (*FetchBtcUtxoResp, error)
	FetchBtcBalance(ctx context.Context, in *FetchBtcBalanceReq, opts ...grpc.CallOption) (*FetchBtcBalanceResp, error)
	GetBtcAddressBalance(ctx context.Context, in *BtcAddressBalanceReq, opts ...grpc.CallOption) (*BtcAddressBalanceResp, error)
	GetBtcAddressUtxo(ctx context.Context, in *BtcAddressUtxoReq, opts ...grpc.CallOption) (*BtcAddressUtxoResp, error)
	GetBtcAddressTx(ctx context.Context, in *BtcAddressTxReq, opts ...grpc.CallOption) (*BtcAddressTxResp, error)
	GetBtcAddressTxCount(ctx context.Context, in *BtcAddressTxCountReq, opts ...grpc.CallOption) (*BtcAddressTxCountResp, error)
	GetBtcTxRaw(ctx context.Context, in *BtcTxRawReq, opts ...grpc.CallOption) (*BtcTxRawResp, error)
	GetBtcFeeRate(ctx context.Context, in *BtcFeeRateReq, opts ...grpc.CallOption) (*BtcFeeRateResp, error)
}

type btcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBtcServiceClient(cc grpc.ClientConnInterface) BtcServiceClient {
	return &btcServiceClient{cc}
}

func (c *btcServiceClient) CheckUtxoInfo(ctx context.Context, in *CheckUtxoInfoReq, opts ...grpc.CallOption) (*CheckUtxoInfoResp, error) {
	out := new(CheckUtxoInfoResp)
	err := c.cc.Invoke(ctx, BtcService_CheckUtxoInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) FetchTxRaw(ctx context.Context, in *FetchTxRawReq, opts ...grpc.CallOption) (*FetchTxRawResp, error) {
	out := new(FetchTxRawResp)
	err := c.cc.Invoke(ctx, BtcService_FetchTxRaw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) BtcBroadcastTx(ctx context.Context, in *BtcBroadcastTxReq, opts ...grpc.CallOption) (*BtcBroadcastTxResp, error) {
	out := new(BtcBroadcastTxResp)
	err := c.cc.Invoke(ctx, BtcService_BtcBroadcastTx_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) BtcCheckTxInfo(ctx context.Context, in *BtcCheckTxInfoReq, opts ...grpc.CallOption) (*BtcCheckTxInfoResp, error) {
	out := new(BtcCheckTxInfoResp)
	err := c.cc.Invoke(ctx, BtcService_BtcCheckTxInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) FetchBtcUtxo(ctx context.Context, in *FetchBtcUtxoReq, opts ...grpc.CallOption) (*FetchBtcUtxoResp, error) {
	out := new(FetchBtcUtxoResp)
	err := c.cc.Invoke(ctx, BtcService_FetchBtcUtxo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) FetchBtcBalance(ctx context.Context, in *FetchBtcBalanceReq, opts ...grpc.CallOption) (*FetchBtcBalanceResp, error) {
	out := new(FetchBtcBalanceResp)
	err := c.cc.Invoke(ctx, BtcService_FetchBtcBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) GetBtcAddressBalance(ctx context.Context, in *BtcAddressBalanceReq, opts ...grpc.CallOption) (*BtcAddressBalanceResp, error) {
	out := new(BtcAddressBalanceResp)
	err := c.cc.Invoke(ctx, BtcService_GetBtcAddressBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) GetBtcAddressUtxo(ctx context.Context, in *BtcAddressUtxoReq, opts ...grpc.CallOption) (*BtcAddressUtxoResp, error) {
	out := new(BtcAddressUtxoResp)
	err := c.cc.Invoke(ctx, BtcService_GetBtcAddressUtxo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) GetBtcAddressTx(ctx context.Context, in *BtcAddressTxReq, opts ...grpc.CallOption) (*BtcAddressTxResp, error) {
	out := new(BtcAddressTxResp)
	err := c.cc.Invoke(ctx, BtcService_GetBtcAddressTx_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) GetBtcAddressTxCount(ctx context.Context, in *BtcAddressTxCountReq, opts ...grpc.CallOption) (*BtcAddressTxCountResp, error) {
	out := new(BtcAddressTxCountResp)
	err := c.cc.Invoke(ctx, BtcService_GetBtcAddressTxCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) GetBtcTxRaw(ctx context.Context, in *BtcTxRawReq, opts ...grpc.CallOption) (*BtcTxRawResp, error) {
	out := new(BtcTxRawResp)
	err := c.cc.Invoke(ctx, BtcService_GetBtcTxRaw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *btcServiceClient) GetBtcFeeRate(ctx context.Context, in *BtcFeeRateReq, opts ...grpc.CallOption) (*BtcFeeRateResp, error) {
	out := new(BtcFeeRateResp)
	err := c.cc.Invoke(ctx, BtcService_GetBtcFeeRate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BtcServiceServer is the server API for BtcService service.
// All implementations must embed UnimplementedBtcServiceServer
// for forward compatibility
type BtcServiceServer interface {
	CheckUtxoInfo(context.Context, *CheckUtxoInfoReq) (*CheckUtxoInfoResp, error)
	FetchTxRaw(context.Context, *FetchTxRawReq) (*FetchTxRawResp, error)
	BtcBroadcastTx(context.Context, *BtcBroadcastTxReq) (*BtcBroadcastTxResp, error)
	BtcCheckTxInfo(context.Context, *BtcCheckTxInfoReq) (*BtcCheckTxInfoResp, error)
	FetchBtcUtxo(context.Context, *FetchBtcUtxoReq) (*FetchBtcUtxoResp, error)
	FetchBtcBalance(context.Context, *FetchBtcBalanceReq) (*FetchBtcBalanceResp, error)
	GetBtcAddressBalance(context.Context, *BtcAddressBalanceReq) (*BtcAddressBalanceResp, error)
	GetBtcAddressUtxo(context.Context, *BtcAddressUtxoReq) (*BtcAddressUtxoResp, error)
	GetBtcAddressTx(context.Context, *BtcAddressTxReq) (*BtcAddressTxResp, error)
	GetBtcAddressTxCount(context.Context, *BtcAddressTxCountReq) (*BtcAddressTxCountResp, error)
	GetBtcTxRaw(context.Context, *BtcTxRawReq) (*BtcTxRawResp, error)
	GetBtcFeeRate(context.Context, *BtcFeeRateReq) (*BtcFeeRateResp, error)
	mustEmbedUnimplementedBtcServiceServer()
}

// UnimplementedBtcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBtcServiceServer struct {
}

func (UnimplementedBtcServiceServer) CheckUtxoInfo(context.Context, *CheckUtxoInfoReq) (*CheckUtxoInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUtxoInfo not implemented")
}
func (UnimplementedBtcServiceServer) FetchTxRaw(context.Context, *FetchTxRawReq) (*FetchTxRawResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchTxRaw not implemented")
}
func (UnimplementedBtcServiceServer) BtcBroadcastTx(context.Context, *BtcBroadcastTxReq) (*BtcBroadcastTxResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BtcBroadcastTx not implemented")
}
func (UnimplementedBtcServiceServer) BtcCheckTxInfo(context.Context, *BtcCheckTxInfoReq) (*BtcCheckTxInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BtcCheckTxInfo not implemented")
}
func (UnimplementedBtcServiceServer) FetchBtcUtxo(context.Context, *FetchBtcUtxoReq) (*FetchBtcUtxoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchBtcUtxo not implemented")
}
func (UnimplementedBtcServiceServer) FetchBtcBalance(context.Context, *FetchBtcBalanceReq) (*FetchBtcBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchBtcBalance not implemented")
}
func (UnimplementedBtcServiceServer) GetBtcAddressBalance(context.Context, *BtcAddressBalanceReq) (*BtcAddressBalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBtcAddressBalance not implemented")
}
func (UnimplementedBtcServiceServer) GetBtcAddressUtxo(context.Context, *BtcAddressUtxoReq) (*BtcAddressUtxoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBtcAddressUtxo not implemented")
}
func (UnimplementedBtcServiceServer) GetBtcAddressTx(context.Context, *BtcAddressTxReq) (*BtcAddressTxResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBtcAddressTx not implemented")
}
func (UnimplementedBtcServiceServer) GetBtcAddressTxCount(context.Context, *BtcAddressTxCountReq) (*BtcAddressTxCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBtcAddressTxCount not implemented")
}
func (UnimplementedBtcServiceServer) GetBtcTxRaw(context.Context, *BtcTxRawReq) (*BtcTxRawResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBtcTxRaw not implemented")
}
func (UnimplementedBtcServiceServer) GetBtcFeeRate(context.Context, *BtcFeeRateReq) (*BtcFeeRateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBtcFeeRate not implemented")
}
func (UnimplementedBtcServiceServer) mustEmbedUnimplementedBtcServiceServer() {}

// UnsafeBtcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BtcServiceServer will
// result in compilation errors.
type UnsafeBtcServiceServer interface {
	mustEmbedUnimplementedBtcServiceServer()
}

func RegisterBtcServiceServer(s grpc.ServiceRegistrar, srv BtcServiceServer) {
	s.RegisterService(&BtcService_ServiceDesc, srv)
}

func _BtcService_CheckUtxoInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUtxoInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).CheckUtxoInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_CheckUtxoInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).CheckUtxoInfo(ctx, req.(*CheckUtxoInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_FetchTxRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTxRawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).FetchTxRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_FetchTxRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).FetchTxRaw(ctx, req.(*FetchTxRawReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_BtcBroadcastTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtcBroadcastTxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).BtcBroadcastTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_BtcBroadcastTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).BtcBroadcastTx(ctx, req.(*BtcBroadcastTxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_BtcCheckTxInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtcCheckTxInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).BtcCheckTxInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_BtcCheckTxInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).BtcCheckTxInfo(ctx, req.(*BtcCheckTxInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_FetchBtcUtxo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchBtcUtxoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).FetchBtcUtxo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_FetchBtcUtxo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).FetchBtcUtxo(ctx, req.(*FetchBtcUtxoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_FetchBtcBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchBtcBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).FetchBtcBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_FetchBtcBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).FetchBtcBalance(ctx, req.(*FetchBtcBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_GetBtcAddressBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtcAddressBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).GetBtcAddressBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_GetBtcAddressBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).GetBtcAddressBalance(ctx, req.(*BtcAddressBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_GetBtcAddressUtxo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtcAddressUtxoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).GetBtcAddressUtxo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_GetBtcAddressUtxo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).GetBtcAddressUtxo(ctx, req.(*BtcAddressUtxoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_GetBtcAddressTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtcAddressTxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).GetBtcAddressTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_GetBtcAddressTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).GetBtcAddressTx(ctx, req.(*BtcAddressTxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_GetBtcAddressTxCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtcAddressTxCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).GetBtcAddressTxCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_GetBtcAddressTxCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).GetBtcAddressTxCount(ctx, req.(*BtcAddressTxCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_GetBtcTxRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtcTxRawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).GetBtcTxRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_GetBtcTxRaw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).GetBtcTxRaw(ctx, req.(*BtcTxRawReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BtcService_GetBtcFeeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BtcFeeRateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BtcServiceServer).GetBtcFeeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BtcService_GetBtcFeeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BtcServiceServer).GetBtcFeeRate(ctx, req.(*BtcFeeRateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BtcService_ServiceDesc is the grpc.ServiceDesc for BtcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BtcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.BtcService",
	HandlerType: (*BtcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUtxoInfo",
			Handler:    _BtcService_CheckUtxoInfo_Handler,
		},
		{
			MethodName: "FetchTxRaw",
			Handler:    _BtcService_FetchTxRaw_Handler,
		},
		{
			MethodName: "BtcBroadcastTx",
			Handler:    _BtcService_BtcBroadcastTx_Handler,
		},
		{
			MethodName: "BtcCheckTxInfo",
			Handler:    _BtcService_BtcCheckTxInfo_Handler,
		},
		{
			MethodName: "FetchBtcUtxo",
			Handler:    _BtcService_FetchBtcUtxo_Handler,
		},
		{
			MethodName: "FetchBtcBalance",
			Handler:    _BtcService_FetchBtcBalance_Handler,
		},
		{
			MethodName: "GetBtcAddressBalance",
			Handler:    _BtcService_GetBtcAddressBalance_Handler,
		},
		{
			MethodName: "GetBtcAddressUtxo",
			Handler:    _BtcService_GetBtcAddressUtxo_Handler,
		},
		{
			MethodName: "GetBtcAddressTx",
			Handler:    _BtcService_GetBtcAddressTx_Handler,
		},
		{
			MethodName: "GetBtcAddressTxCount",
			Handler:    _BtcService_GetBtcAddressTxCount_Handler,
		},
		{
			MethodName: "GetBtcTxRaw",
			Handler:    _BtcService_GetBtcTxRaw_Handler,
		},
		{
			MethodName: "GetBtcFeeRate",
			Handler:    _BtcService_GetBtcFeeRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/btc_service/btc_service.proto",
}
